name: Docker compose test pipeline

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Fedora Pod
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.HETZNER_KUBE_CONFIG }}
        with:
          args: apply -f docker-compose/podman.yaml

      - name: Wait for pod to be ready
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.HETZNER_KUBE_CONFIG }}
        with:
          args: wait --for=condition=ready pod -l app=podman-priv --timeout=120s


      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.HETZNER_KUBE_CONFIG }}
      - name: Get Pod Name
        id: get-pod
        run: echo "POD_NAME=$(kubectl get pods -l app=podman-priv -o jsonpath='{.items[0].metadata.name}')" >> "$GITHUB_OUTPUT"

      - name: Print Pod Name
        env:
          POD_NAME: ${{ steps.get-pod.outputs.POD_NAME }}
        run: echo "$POD_NAME"

      - name: Run Tests
        run : kubectl exec --stdin --tty ${{ steps.get-pod.outputs.POD_NAME }}  -- bash -c "cd waltid-identity/docker-compose && pip3 install requests && python3 api-test.py"

