name: Docker compose test

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Fedora Pod
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.HETZNER_KUBE_CONFIG }}
        with:
          args: apply -f docker-compose/podman.yaml

      - name: Wait for pod to be ready
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.HETZNER_KUBE_CONFIG }}
        with:
          args: wait --for=condition=ready pod -l app=podman-priv --timeout=120s

      - name: Run Tests
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.HETZNER_KUBE_CONFIG }}
        with:
          args: exec -it $(kubectl get pods -l app=podman-priv -o jsonpath="{.items[0].metadata.name}") -- bash -c "cd waltid-identity/docker-compose && pip3 install requests && python3 test-script.py"

#      - name: Generate Test Reports
#        uses: actions-hub/kubectl@master
#        env:
#          KUBE_CONFIG: ${{ secrets.HETZNER_KUBE_CONFIG }}
#        with:
#          args: cp $(kubectl get pods -l app=podman-priv -o jsonpath="{.items[0].metadata.name}"):/path/to/report ./report
#        # Upload report to GitHub or any other artifact storage
#
#      - name: Upload Test Reports
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-report
#          path: ./report
