name: Deploy manually to test environment

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Custom version'
        required: false
jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@feat/test-self-hosted-runners
    with:
      preferred: ${{ inputs.release_version }}
  gradle-build:
    uses: walt-id/waltid-identity/.github/workflows/build-gradle.yml@feat/test-self-hosted-runners
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-build:
    uses: walt-id/waltid-identity/.github/workflows/build-docker.yml@feat/test-self-hosted-runners
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@feat/test-self-hosted-runners
    needs: [ version, gradle-build, docker-build ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    needs: [ version, deploy ]
    steps:
      - run: |
          git tag v${{ needs.version.outputs.release_version }}
          git push --tags