name: Deploy manually to test environment

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Custom version'
        required: false
jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@c69d2155372700071dad887fa6339b51e0266be5
    with:
      preferred: ${{ inputs.release_version }}
  gradle-build:
    uses: walt-id/waltid-identity/.github/workflows/build-gradle.yml@c69d2155372700071dad887fa6339b51e0266be5
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-build:
    uses: walt-id/waltid-identity/.github/workflows/build-docker.yml@c69d2155372700071dad887fa6339b51e0266be5
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@c69d2155372700071dad887fa6339b51e0266be5
    secrets: inherit
    needs: [ version, gradle-build, docker-build ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@854a65fa2d05b330917b33846441e410b3c8034c
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}